### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by CrazyH2** [LabyStudio/js-minecraft#11]
@LabyStudio how do i setup a server?
I would love to carry on this project but this is a major block

**Comment by kiliansinger** [comment]
I set it up properly. In a few weeks I will issue a pull request with all details. Some server side commands needed to be additionally implemented. But it works flawlessly.

**Comment by CrazyH2** [comment]
> I set it up properly. In a few weeks I will issue a pull request with all details. Some server side commands needed to be additionally implemented. But it works flawlessly. But I needed to do more than 50 commits to get it right.
> Now the final step missing is saving the state in singleplayer mode in indexdb. But I think I should get it running in the next few days. I also implemented a blocklike programming language. So you can have tnt exploding. Why I am not yet opening the pull request is that i need to search for possible copyright and trademark issues and also fix the history if necessary.

how is it going?

**Comment by kiliansinger** [comment]
I am currently waiting for the clarification of the license. As the current situation is that forking on github only no changes is the only legally fully compliant way.

**Comment by kiliansinger** [comment]
Great news,
the project is under non-commercial creative common license. X-mas time is great to do the final fixes. So stay tuned.

**Comment by CrazyH2** [comment]
> Great news,
> the project is under non-commercial creative common license. X-mas time is great to do the final fixes. So stay tuned.

good? @kiliansinger

**Comment by kiliansinger** [comment]
Done.

**Comment by CrazyH2** [comment]
> Done.

@kiliansinger 
It looks great :)
Im going to add a world select menu and do the same for servers but imma add a limit of saved servers and saved worlds you can have what should it be? I'm thinking 20 servers and 4 worlds. I could save the worlds in a server somewhere else

**Comment by kiliansinger** [comment]
also checkout the programming environment: https://mintrobi.de/block
and press c. if you have functions you can use them in the chat dialog...
here are some programs e.g. tnt: https://mintrobi.de/teach/mintblockprogramme/

**Comment by kiliansinger** [comment]
It does not happen to me. I am using chrome. is this happening in firefox?

**Comment by CrazyH2** [comment]
> ppens on your git clone. You need to have python environment and do npm i, npm run build in the blockly_git folder. But we should discuss theses things

it happens when using mintblock @kiliansinger I use chrome latest

**Comment by kiliansinger** [comment]
could you post an issue on my github with all details, operating system, local install, hosted webpage, or my install. I need to reproduce the problem to fix it.

**Comment by kiliansinger** [comment]
Oh I reproduced it. you need as shortly described above do:
start python environment (e.g miniconda)
then:

cd blockly_git
npm i
npm run build

**Comment by CrazyH2** [comment]
> Oh I reproduced it. you need as shortly described above do: start python environment (e.g miniconda) then:
> 
> cd blockly_git npm i npm run build

I know but when I use the public hosted version of mintblock it still happens :/ @kiliansinger

**Comment by kiliansinger** [comment]
lets continue this on my github as an issue, I do not want to hijack this channel...

**Comment by CrazyH2** [comment]
> lets continue this on my github as an issue, I do not want to hijack this channel...

i cant open issues on your github and the issue I'm talking about also happens with the original

**Comment by CrazyH2** [comment]
@kiliansinger the issue seems to be with the background as the main menu doesn't have the problem as it has a panorama and all the buttons and text on other menus still show while it flickers.

**Comment by kiliansinger** [comment]
Oh I need to figure out how to allow issue posting. But with original you mean:
https://labystudio.de/page/minecraft/

Which OS are you using. Does it also happen on other computers you might have access to? It might be something that cannot dynamically load. There is a cool method called git bisect. It is binary search and one can find the commit that introduced the incompatbility even if it just affects one specific constellation of system.

**Comment by CrazyH2** [comment]
> Oh I need to figure out how to allow issue posting. But with original you mean: https://labystudio.de/page/minecraft/
> 
> Which OS are you using. Does it also happen on other computers you might have access to? It might be something that cannot dynamically load. There is a cool method called git bisect. It is binary search and one can find the commit that introduced the incompatbility even if it just affects one specific constellation of system.
> 
> Did you try running the code locally? I am using vs-code with the live-server plugin: https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer
> 
> you can do a: git clone https://https://github.com/kiliansinger/mintblock then checkout the version without blockly (the pullrequest) git checkout labystudio_pullrequest
> 
> then open vs-code and start the live-server. and do a git bisect to find the commit that introduced the problem. No worries as it is binary search it takes only about 8 tries to find the one. Here is a tutorial: https://www.metaltoad.com/blog/beginners-guide-git-bisect-process-elimination

@kiliansinger don't worry I have fixed it with a work around.
<img width="1212" alt="Screenshot 2024-01-12 at 21 37 19" src="https://github.com/LabyStudio/js-minecraft/assets/87752773/5af21010-9b3f-4e7d-9b71-0c197402a22a">

I have started making a world select menu

**Comment by kiliansinger** [comment]
looks great, i allowd for issues on my git now.

**Comment by CrazyH2** [comment]
> looks great, i allowd for issues on my git now.

@kiliansinger do you have discord? I think it will be easier to contact each other.

**Comment by kiliansinger** [comment]
no don't have it

**Comment by CrazyH2** [comment]
> Oh I reproduced it. you need as shortly described above do: start python environment (e.g miniconda) then:
> 
> cd blockly_git npm i npm run build

@kiliansinger, yo what happened? I have finish the world page by the way.
