### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by FlySkyPie** [LabyStudio/js-minecraft#4]
Hi, nice work!
Does this project is open source?
If so, can you provide License?
I'd like to refactoring this project in Typescript and other modern setup of javascript .

**Comment by LabyStudio** [comment]
Thanks!
You can fork the project and can change the code but you are not allowed to remove any kind of credits.

**Comment by FlySkyPie** [comment]
> Thanks! You can fork the project and can change the code but you are not allowed to remove any kind of credits.

What's I means is that, beside third party library, 
can you pick up a open source license, e.g. MIT, LGPL, and provide `LICENSE.md` inside project?
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
