### ISSUE TITLE
Refactoring this app 

### ISSUE THREAD

**Issue by ekmas** [LabyStudio/js-minecraft#5]
Hi, I like this project a lot. The main issue with why the app is so laggy is that you literally added whole libraries to this app. I think the better approach would be to use npm to install all these libraries and then use a module bundler like webpack or rollup.

I can help you with that if you're interested :D

**Comment by LabyStudio** [comment]
The reason I refused to use such tools is that I never wanted to achieve anything with this project.
For me, it was just a way to pass the time during school so I had something to jump around when I was bored.

I also wanted to understand and document all the important features of the Minecraft rendering engine.
So the focus for me is more on the code and being able to debug it without issues.
Compiling it into a big garbage only makes it worse to debug it in the browser.

**Comment by LabyStudio** [comment]
But of course it only makes sense to refactor it in order to implement it correctly.
But to be honest, I would just rewrite it right away if I had the time 😅

**Comment by CrazyH2** [comment]
> But of course it only makes sense to refactor it in order to implement it correctly.
> 
> But to be honest, I would just rewrite it right away if I had the time 😅

@LabyStudio 

Hi, I just wanted to say that Kleat has improved the fps a lot. It was bad due to the font rendering as it was rendering every single character from a image file rather that using a normal font and importing that. Heres the github commit:

**Comment by bitlogist** [comment]
Thank you, @CrazyH2 that information was very useful. Thank you, @LabyStudio for making the best repo I've ever seen in my life. I just think it would be nice to save changes made by players in the default multiplayer server.

**Comment by CrazyH2** [comment]
> Thank you, @CrazyH2 that information was very useful. Thank you, @LabyStudio for making the best repo I've ever seen in my life. I just think it would be nice to save changes made by players in the default multiplayer server.

Your welcome. I am currently improving this project a bunch, and have made it so you can join any cracked server and build and place blocks with the help of someone else.

**Comment by bitlogist** [comment]
> > Thank you, @CrazyH2 that information was very useful. Thank you, @LabyStudio for making the best repo I've ever seen in my life. I just think it would be nice to save changes made by players in the default multiplayer server.
> 
> Your welcome. I am currently improving this project a bunch, and have made it so you can join any cracked server and build and place blocks with the help of someone else.

I am working on a survival mode because it would be so fun to play survival in the browser.

**Comment by CrazyH2** [comment]
> > > Thank you, @CrazyH2 that information was very useful. Thank you, @LabyStudio for making the best repo I've ever seen in my life. I just think it would be nice to save changes made by players in the default multiplayer server.
> > 
> > 
> > Your welcome. I am currently improving this project a bunch, and have made it so you can join any cracked server and build and place blocks with the help of someone else.
> 
> I am working on a survival mode because it would be so fun to play survival in the browser.

@bitlogist, How is it going?

**Comment by bitlogist** [comment]
It's going well. I managed to render tools (an iron pickaxe) by making them special blocks.

**Comment by bitlogist** [comment]
My friend, @intfract, has a [repo](/intfract/minecraft) with these changes.

**Comment by CrazyH2** [comment]
> My friend, @intfract, has a [repo](/intfract/minecraft) with these changes.

Ok, thanks I will take a look
